"use client";
import { useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { ChevronDown, Heart, LockKeyhole, RotateCcw, ShieldCheck, ShoppingBag, Star, Truck, ZoomIn } from "lucide-react";
import Header from "../Header"; import Footer from "../Footer"; import ProductCard from "../ProductCard"; import { useApp } from "../AppContext";

export default function ProductPage(){
 const {id}=useParams<{id:string}>(); const {products,addToCart,setIsCartOpen}=useApp(); const product=products.find(p=>p.id===Number(id));
 const [active,setActive]=useState(0); const [size,setSize]=useState<string|null>(null); const [color,setColor]=useState<string|null>(null); const [qty,setQty]=useState(1); const [added,setAdded]=useState(false);
 const gallery=useMemo(()=>product?[product.image,...(product.images||[]).filter(x=>x!==product.image)]:[],[product]);
 if(!product)return <div className="commerce-page"><Header/><main className="product-loading"><h1>Đang tải sản phẩm...</h1><p>Nếu sản phẩm không xuất hiện, vui lòng quay lại trang sản phẩm.</p><a className="btn-primary" href="/shop">Xem sản phẩm</a></main><Footer/></div>;
 const productId=product.id; const sale=product.discount_price!=null&&product.discount_price<product.price; const current=sale?product.discount_price!:product.price; const rating=product.reviews?.length?product.reviews.reduce((s,r)=>s+r.rating,0)/product.reviews.length:4.9;
 async function buy(){await addToCart(productId,qty,size,color);setAdded(true);setTimeout(()=>setAdded(false),1800);setIsCartOpen(true)}
 return <div className="commerce-page"><Header/><main className="product-page">
  <div className="breadcrumbs">Trang chủ <span>/</span> Áo thun <span>/</span> {product.name}</div>
  <section className="product-purchase">
   <div className="gallery"><div className="thumbs">{gallery.map((img,i)=><button key={`${img}-${i}`} className={active===i?"active":""} onClick={()=>setActive(i)}><img src={img} alt={`${product.name} ${i+1}`}/></button>)}</div><div className="main-image"><img src={gallery[active]||product.image} alt={product.name}/><span><ZoomIn size={16}/> Phóng to</span></div></div>
   <div className="purchase-panel"><h1>{product.name}</h1><div className="rating-line"><Star fill="currentColor"/> {rating.toFixed(1)} ({product.reviews?.length||128} đánh giá) <span/> Đã bán 326</div><div className="detail-price"><strong>{current.toLocaleString("vi-VN")}đ</strong>{sale?<><del>{product.price.toLocaleString("vi-VN")}đ</del><em>-{Math.round((product.price-current)/product.price*100)}%</em></>:null}</div><p className="product-description">{product.description||"Thiết kế biểu tượng MOUSEEE mang tinh thần kết nối không biên giới. Form oversize thoải mái, chất liệu cotton cao cấp và họa tiết in sắc nét."}</p>
    <Option title={`Màu sắc${color?`: ${color}`:""}`}><div className="option-buttons">{(product.colors.length?product.colors:["Đen","Trắng","Xám"]).map(x=><button className={color===x?"selected":""} onClick={()=>setColor(x)} key={x}>{x}</button>)}</div></Option>
    <Option title="Kích thước" extra="Hướng dẫn chọn size"><div className="size-buttons">{(product.sizes.length?product.sizes:["XS","S","M","L","XL"]).map(x=><button className={size===x?"selected":""} onClick={()=>setSize(x)} key={x}>{x}</button>)}</div></Option>
    <div className="stock-status">● {product.stock>0?`Còn hàng (${product.stock} sản phẩm)`:"Hết hàng"}</div><div className="qty-row"><strong>Số lượng</strong><div><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><span>{qty}</span><button onClick={()=>setQty(Math.min(product.stock||1,qty+1))}>+</button></div></div>
    <button className="add-cart-large" onClick={buy} disabled={product.stock<1}><ShoppingBag/> {added?"Đã thêm vào giỏ!":"Thêm vào giỏ hàng"}</button><button className="buy-now" onClick={buy}>Mua ngay</button><button className="wishlist"><Heart/> Thêm vào danh sách yêu thích</button>
    <div className="detail-trust"><span><Truck/><small>Miễn phí vận chuyển<br/>từ 499.000đ</small></span><span><RotateCcw/><small>Đổi trả trong<br/>30 ngày</small></span><span><LockKeyhole/><small>Thanh toán<br/>an toàn</small></span><span><ShieldCheck/><small>Sản phẩm<br/>chính hãng</small></span></div>
   </div>
  </section>
  <section className="product-info-section"><div className="accordions"><Info title="Mô tả sản phẩm" open><p>Form oversized mang đến vẻ ngoài phóng khoáng, dễ phối cùng quần jeans, cargo hoặc short. Họa tiết được in bằng công nghệ cao, bền màu sau nhiều lần giặt.</p></Info><Info title="Chất liệu & bảo quản"/><Info title="Thông tin giao hàng"/></div><div className="size-guide"><div className="section-heading"><h2>Bảng size & form dáng</h2><a>Hướng dẫn đo</a></div><table><thead><tr><th>Size</th><th>S</th><th>M</th><th>L</th><th>XL</th></tr></thead><tbody><tr><td>Dài áo (cm)</td><td>70</td><td>72</td><td>74</td><td>76</td></tr><tr><td>Ngang ngực (cm)</td><td>58</td><td>60</td><td>62</td><td>64</td></tr><tr><td>Chiều cao (cm)</td><td>160–170</td><td>165–175</td><td>170–180</td><td>175–185</td></tr></tbody></table></div></section>
  <section className="review-section"><h2>Đánh giá sản phẩm</h2><div className="review-summary"><div><strong>{rating.toFixed(1)}</strong><span>/5</span><div className="stars">★★★★★</div><p>({product.reviews?.length||128} đánh giá)</p></div><div className="rating-bars">{[5,4,3,2,1].map((n,i)=><div key={n}>{n} ★ <span><i style={{width:`${[88,22,8,3,1][i]}%`}}/></span></div>)}</div></div><div className="review-list">{(product.reviews?.length?product.reviews:[{id:1,username:"Minh Đức",rating:5,comment:"Áo đẹp, form rộng đúng gu, vải dày dặn mặc lên rất thích. Họa tiết in sắc nét, không bong tróc.",created_at:"2026-07-11"},{id:2,username:"Hoàng Nam",rating:5,comment:"Chất cotton mềm mát. Mình mặc size M vừa oversize như mong muốn. Giao hàng nhanh, đóng gói cẩn thận.",created_at:"2026-07-09"}]).map(r=><article key={r.id}><strong>{r.username} <small>✓ Đã mua hàng</small></strong><div className="stars">{"★".repeat(r.rating)}</div><p>{r.comment}</p></article>)}</div></section>
  <section className="content-section"><div className="section-heading"><h2>Phối cùng sản phẩm này</h2></div><div className="products-grid">{products.filter(p=>p.id!==product.id).slice(0,4).map(p=><ProductCard key={p.id} id={p.id} title={p.name} price={p.price} discount_price={p.discount_price} img={p.image} colors={p.colors} stock={p.stock}/>)}</div></section>
 </main><Footer/></div>
}
function Option({title,extra,children}:{title:string;extra?:string;children:React.ReactNode}){return <div className="detail-option"><div><strong>{title}</strong>{extra?<a>{extra}</a>:null}</div>{children}</div>}
function Info({title,open,children}:{title:string;open?:boolean;children?:React.ReactNode}){return <details open={open}><summary>{title}<ChevronDown/></summary>{children}</details>}
